-- Fix CityMall tables schema to match updated definitions
-- This addresses the VARCHAR padding issues and ensures proper data insertion

BEGIN;

-- Drop existing tables if they have wrong structure and recreate them
-- Note: This will delete existing test data
DROP TABLE IF EXISTS city_mall_po_lines CASCADE;
DROP TABLE IF EXISTS city_mall_po_header CASCADE;

-- Create CityMall PO Header table with correct schema
CREATE TABLE city_mall_po_header (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    po_number VARCHAR(50) NOT NULL,
    po_date TIMESTAMP,
    po_expiry_date TIMESTAMP,
    vendor_name TEXT,
    vendor_gstin TEXT,
    vendor_code TEXT,
    status VARCHAR(20) DEFAULT 'Open',
    total_quantity INTEGER DEFAULT 0,
    total_base_amount DECIMAL(15,2) DEFAULT 0,
    total_igst_amount DECIMAL(15,2) DEFAULT 0,
    total_cess_amount DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) DEFAULT 0,
    unique_hsn_codes TEXT[],
    created_by VARCHAR(100),
    uploaded_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create CityMall PO Lines table
CREATE TABLE city_mall_po_lines (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    po_header_id INTEGER REFERENCES city_mall_po_header(id) ON DELETE CASCADE,
    line_number INTEGER NOT NULL,
    article_id VARCHAR(50),
    article_name TEXT,
    hsn_code VARCHAR(20),
    mrp DECIMAL(10,2),
    base_cost_price DECIMAL(10,2),
    quantity INTEGER DEFAULT 0,
    base_amount DECIMAL(15,2),
    igst_percent DECIMAL(5,2),
    cess_percent DECIMAL(5,2),
    igst_amount DECIMAL(10,2),
    cess_amount DECIMAL(10,2),
    total_amount DECIMAL(15,2),
    status VARCHAR(20) DEFAULT 'Pending',
    created_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX idx_city_mall_po_header_po_number ON city_mall_po_header(po_number);
CREATE INDEX idx_city_mall_po_header_created_at ON city_mall_po_header(created_at);
CREATE INDEX idx_city_mall_po_lines_po_header_id ON city_mall_po_lines(po_header_id);

-- Verify the structure
\d city_mall_po_header;
\d city_mall_po_lines;

COMMIT;

-- Test the tables work
INSERT INTO city_mall_po_header (po_number, vendor_name, vendor_gstin, total_amount, created_by)
VALUES ('TEST-SCHEMA-FIX', 'Test Vendor', 'TEST123456789', 100.00, 'schema-fix-test');

SELECT id, po_number, vendor_name, vendor_gstin FROM city_mall_po_header WHERE po_number = 'TEST-SCHEMA-FIX';

-- Clean up test
DELETE FROM city_mall_po_header WHERE po_number = 'TEST-SCHEMA-FIX';