-- CORRECTED Zepto PO Schema
-- Drop existing tables if they have issues
DROP TABLE IF EXISTS public.zepto_po_lines CASCADE;
DROP TABLE IF EXISTS public.zepto_po_header CASCADE;

-- Create zepto_po_header table
CREATE TABLE IF NOT EXISTS public.zepto_po_header
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    po_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    po_date timestamp without time zone,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'Open'::character varying,
    vendor_code character varying(50) COLLATE pg_catalog."default",
    vendor_name character varying(200) COLLATE pg_catalog."default",
    po_amount numeric(15,2),
    delivery_location character varying(200) COLLATE pg_catalog."default",
    po_expiry_date timestamp without time zone,
    total_quantity integer DEFAULT 0,
    total_cost_value numeric(15,2) DEFAULT '0'::numeric,
    total_tax_amount numeric(15,2) DEFAULT '0'::numeric,
    total_amount numeric(15,2) DEFAULT '0'::numeric,
    unique_brands text[] COLLATE pg_catalog."default",
    created_by character varying(100) COLLATE pg_catalog."default",
    uploaded_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT zepto_po_header_pkey PRIMARY KEY (id)
);

-- Create zepto_po_lines table
CREATE TABLE IF NOT EXISTS public.zepto_po_lines
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    po_header_id integer,
    line_number integer NOT NULL,
    po_number character varying(50) COLLATE pg_catalog."default",
    sku text COLLATE pg_catalog."default",
    sku_desc text COLLATE pg_catalog."default",
    brand character varying(100) COLLATE pg_catalog."default",
    sku_id character varying(100) COLLATE pg_catalog."default",
    sap_id character varying(50) COLLATE pg_catalog."default",
    hsn_code character varying(50) COLLATE pg_catalog."default",
    ean_no character varying(50) COLLATE pg_catalog."default",
    po_qty integer DEFAULT 0,
    asn_qty integer DEFAULT 0,
    grn_qty integer DEFAULT 0,
    remaining_qty integer DEFAULT 0,
    cost_price numeric(10,2),
    landing_cost numeric(10,2), -- THIS COLUMN WAS MISSING FROM YOUR ORIGINAL SQL
    cgst numeric(10,2),
    sgst numeric(10,2),
    igst numeric(10,2),
    cess numeric(10,2),
    mrp numeric(10,2),
    total_value numeric(15,2),
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    created_by character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT zepto_po_lines_pkey PRIMARY KEY (id),
    CONSTRAINT zepto_po_lines_po_header_id_fkey FOREIGN KEY (po_header_id)
        REFERENCES public.zepto_po_header (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);