-- Create states_mst table
CREATE TABLE IF NOT EXISTS "states_mst" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "state_name" varchar(100) NOT NULL UNIQUE,
  "state_code" varchar(10) UNIQUE,
  "region" varchar(50),
  "status" varchar(20) NOT NULL DEFAULT 'Active',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

-- Create districts_mst table
CREATE TABLE IF NOT EXISTS "districts_mst" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "district_name" varchar(100) NOT NULL,
  "state_id" integer NOT NULL,
  "district_code" varchar(10),
  "status" varchar(20) NOT NULL DEFAULT 'Active',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  CONSTRAINT "districts_mst_state_id_fk" FOREIGN KEY ("state_id") REFERENCES "states_mst"("id") ON DELETE CASCADE
);

-- Insert sample states
INSERT INTO "states_mst" ("state_name", "state_code", "region") VALUES
  ('Delhi', 'DL', 'North'),
  ('Karnataka', 'KA', 'South'),
  ('Maharashtra', 'MH', 'West'),
  ('West Bengal', 'WB', 'East'),
  ('Madhya Pradesh', 'MP', 'Central'),
  ('Tamil Nadu', 'TN', 'South'),
  ('Gujarat', 'GJ', 'West'),
  ('Haryana', 'HR', 'North'),
  ('Punjab', 'PB', 'North')
ON CONFLICT (state_name) DO NOTHING;

-- Insert sample districts
INSERT INTO "districts_mst" ("district_name", "state_id") VALUES
  -- Delhi districts
  ('New Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),
  ('Central Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),
  ('South Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),
  ('North Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),
  ('East Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),
  ('West Delhi', (SELECT id FROM states_mst WHERE state_name = 'Delhi')),

  -- Karnataka districts
  ('Bangalore', (SELECT id FROM states_mst WHERE state_name = 'Karnataka')),
  ('Mysore', (SELECT id FROM states_mst WHERE state_name = 'Karnataka')),
  ('Hubli', (SELECT id FROM states_mst WHERE state_name = 'Karnataka')),
  ('Mangalore', (SELECT id FROM states_mst WHERE state_name = 'Karnataka')),
  ('Belgaum', (SELECT id FROM states_mst WHERE state_name = 'Karnataka')),

  -- Maharashtra districts
  ('Mumbai', (SELECT id FROM states_mst WHERE state_name = 'Maharashtra')),
  ('Pune', (SELECT id FROM states_mst WHERE state_name = 'Maharashtra')),
  ('Nagpur', (SELECT id FROM states_mst WHERE state_name = 'Maharashtra')),
  ('Nashik', (SELECT id FROM states_mst WHERE state_name = 'Maharashtra')),
  ('Aurangabad', (SELECT id FROM states_mst WHERE state_name = 'Maharashtra')),

  -- West Bengal districts
  ('Kolkata', (SELECT id FROM states_mst WHERE state_name = 'West Bengal')),
  ('Howrah', (SELECT id FROM states_mst WHERE state_name = 'West Bengal')),
  ('Durgapur', (SELECT id FROM states_mst WHERE state_name = 'West Bengal')),
  ('Siliguri', (SELECT id FROM states_mst WHERE state_name = 'West Bengal')),
  ('Asansol', (SELECT id FROM states_mst WHERE state_name = 'West Bengal')),

  -- Madhya Pradesh districts
  ('Bhopal', (SELECT id FROM states_mst WHERE state_name = 'Madhya Pradesh')),
  ('Indore', (SELECT id FROM states_mst WHERE state_name = 'Madhya Pradesh')),
  ('Gwalior', (SELECT id FROM states_mst WHERE state_name = 'Madhya Pradesh')),
  ('Jabalpur', (SELECT id FROM states_mst WHERE state_name = 'Madhya Pradesh')),
  ('Ujjain', (SELECT id FROM states_mst WHERE state_name = 'Madhya Pradesh'))
ON CONFLICT DO NOTHING;

-- Display results
SELECT 'States created:' as message;
SELECT id, state_name, state_code, region FROM states_mst ORDER BY id;

SELECT 'Districts created:' as message;
SELECT d.id, d.district_name, s.state_name 
FROM districts_mst d 
JOIN states_mst s ON d.state_id = s.id 
ORDER BY s.state_name, d.district_name;